name: nes
description: "NES emulator"
publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  binarize: ^1.5.0
  build_runner: ^2.4.10
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.5.1
  json_annotation: ^4.9.0
  mp_audio_stream:
    path: ../../other/mp-audio-stream
  path: ^1.9.0
  path_provider: ^2.1.3
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  riverpod_generator: ^2.4.0
  shared_preferences: ^2.2.3

dev_dependencies:
  dart_code_metrics: ^5.7.6
  flutter_test:
    sdk: flutter

  freezed: ^2.5.2
  json_serializable: ^6.8.0
  lint: ^2.1.2

flutter:
  uses-material-design: true
