name: nesd
description: "NES emulator"
publish_to: 'none'

version: 0.3.0+dev

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  archive: ^3.6.1
  auto_route: ^8.2.0
  binarize: ^1.5.0
  build_runner: ^2.4.10
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  gamepads:
    git:
      url: https://github.com/jpjonte/gamepads.git
      ref: feature/nesd
      path: packages/gamepads
  hooks_riverpod: ^2.5.1
  json_annotation: ^4.9.0
  mp_audio_stream:
    git:
      url: https://github.com/jpjonte/mp-audio-stream.git
      ref: feature/buffer-size
  package_info_plus: ^8.0.0
  path: ^1.9.0
  path_provider: ^2.1.3
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  riverpod_generator: ^2.4.0
  saf:
    git:
      url: https://github.com/jpjonte/saf.git
      ref: feature/nesd
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0

dev_dependencies:
  auto_route_generator: ^8.0.0
  custom_lint: ^0.6.4
  flutter_test:
    sdk: flutter

  freezed: ^2.5.2
  json_serializable: ^6.8.0
  lint: ^2.1.2
  riverpod_lint: ^2.3.10

dependency_overrides:
  gamepads_darwin:
    git:
      url: https://github.com/jpjonte/gamepads.git
      ref: feature/nesd
      path: packages/gamepads_darwin
  gamepads_linux:
    git:
      url: https://github.com/jpjonte/gamepads.git
      ref: feature/nesd
      path: packages/gamepads_linux
  gamepads_platform_interface:
    git:
      url: https://github.com/jpjonte/gamepads.git
      ref: feature/nesd
      path: packages/gamepads_platform_interface
  gamepads_windows:
    git:
      url: https://github.com/jpjonte/gamepads.git
      ref: feature/nesd
      path: packages/gamepads_windows

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  image_path: "assets/logo.png"
  macos:
    generate: true
  windows:
    generate: true
  android: true

