name: nesd
description: "NES emulator"
publish_to: 'none'

version: 0.9.0

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  archive: ^4.0.2
  auto_route: ^9.2.2
  binarize: ^2.0.0
  build_runner: ^2.4.10
  collection: ^1.18.0
  crypto: ^3.0.5
  file_picker: ^9.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_launcher_icons: ^0.14.1
  flutter_material_design_icons: ^1.1.7447
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  gamepads:
    git:
      url: https://github.com/jpjonte/gamepads.git
      ref: feature/nesd
      path: packages/gamepads
  hooks_riverpod: ^2.5.1
  image: ^4.2.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  mp_audio_stream:
    git:
      url: https://github.com/jpjonte/mp-audio-stream.git
      ref: feature/buffer-size
  package_info_plus: ^8.0.0
  path: ^1.9.0
  path_provider: ^2.1.3
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  riverpod_generator: ^2.4.0
  rxdart: ^0.28.0
  saf:
    git:
      url: https://github.com/jpjonte/saf.git
      ref: feature/nesd
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0

dev_dependencies:
  auto_route_generator: ^9.0.0
  custom_lint: ^0.7.0
  dart_code_metrics_presets: ^2.20.0
  flutter_test:
    sdk: flutter

  freezed: ^2.5.2
  json_serializable: ^6.8.0
  lint: ^2.1.2
  mocktail: ^1.0.4
  riverpod_lint: ^2.3.10

dependency_overrides:
  gamepads_darwin:
    git:
      url: https://github.com/jpjonte/gamepads.git
      ref: feature/nesd
      path: packages/gamepads_darwin
  gamepads_linux:
    git:
      url: https://github.com/jpjonte/gamepads.git
      ref: feature/nesd
      path: packages/gamepads_linux
  gamepads_platform_interface:
    git:
      url: https://github.com/jpjonte/gamepads.git
      ref: feature/nesd
      path: packages/gamepads_platform_interface
  gamepads_windows:
    git:
      url: https://github.com/jpjonte/gamepads.git
      ref: feature/nesd
      path: packages/gamepads_windows

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Ubuntu Mono
      fonts:
        - asset: assets/fonts/UbuntuMono-Regular.ttf
        - asset: assets/fonts/UbuntuMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/UbuntuMono-Italic.ttf
          style: italic
        - asset: assets/fonts/UbuntuMono-BoldItalic.ttf
          weight: 700
          style: italic

flutter_launcher_icons:
  image_path: "assets/logo.png"
  macos:
    generate: true
  windows:
    generate: true
  android: true

