name: nes
description: "NES emulator"
publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^2.1.2

flutter:
  uses-material-design: true
