import 'package:nesd/nes/cpu/address_mode.dart';
import 'package:nesd/nes/cpu/cpu.dart';
import 'package:nesd/nes/cpu/instruction.dart';

class Operation {
  Operation(this.instruction, this.addressMode, {this.unofficial = false});

  final Instruction instruction;
  final AddressMode addressMode;
  final bool unofficial;

  void execute(CPU cpu) {
    addressMode.execute(cpu);
    instruction.execute(cpu);
  }
}

final ops = [
  Operation(BRK(), implicit),
  Operation(ORA(), indexedIndirect),
  Operation(STP(), implicit, unofficial: true),
  Operation(SLO(), indexedIndirect, unofficial: true),
  Operation(NOP(), zeroPage, unofficial: true),
  Operation(ORA(), zeroPage),
  Operation(ASL(), zeroPage),
  Operation(SLO(), zeroPage, unofficial: true),
  Operation(PHP(), implicit),
  Operation(ORA(), immediate),
  Operation(ASL(), accumulator),
  Operation(ANC(), immediate, unofficial: true),
  Operation(NOP(), absolute, unofficial: true),
  Operation(ORA(), absolute),
  Operation(ASL(), absolute),
  Operation(SLO(), absolute, unofficial: true),
  Operation(BPL(), relative),
  Operation(ORA(), indirectIndexed),
  Operation(STP(), implicit, unofficial: true),
  Operation(SLO(), indirectIndexed, unofficial: true),
  Operation(NOP(), zeroPageX, unofficial: true),
  Operation(ORA(), zeroPageX),
  Operation(ASL(), zeroPageX),
  Operation(SLO(), zeroPageX, unofficial: true),
  Operation(CLC(), implicit),
  Operation(ORA(), absoluteY),
  Operation(NOP(), implicit, unofficial: true),
  Operation(SLO(), absoluteY, unofficial: true),
  Operation(NOP(), absoluteX, unofficial: true),
  Operation(ORA(), absoluteX),
  Operation(ASL(), absoluteX),
  Operation(SLO(), absoluteX, unofficial: true),
  Operation(JSR(), absolute),
  Operation(AND(), indexedIndirect),
  Operation(STP(), implicit, unofficial: true),
  Operation(RLA(), indexedIndirect, unofficial: true),
  Operation(BIT(), zeroPage),
  Operation(AND(), zeroPage),
  Operation(ROL(), zeroPage),
  Operation(RLA(), zeroPage, unofficial: true),
  Operation(PLP(), implicit),
  Operation(AND(), immediate),
  Operation(ROL(), accumulator),
  Operation(ANC(), immediate, unofficial: true),
  Operation(BIT(), absolute),
  Operation(AND(), absolute),
  Operation(ROL(), absolute),
  Operation(RLA(), absolute, unofficial: true),
  Operation(BMI(), relative),
  Operation(AND(), indirectIndexed),
  Operation(STP(), implicit, unofficial: true),
  Operation(RLA(), indirectIndexed, unofficial: true),
  Operation(NOP(), zeroPageX, unofficial: true),
  Operation(AND(), zeroPageX),
  Operation(ROL(), zeroPageX),
  Operation(RLA(), zeroPageX, unofficial: true),
  Operation(SEC(), implicit),
  Operation(AND(), absoluteY),
  Operation(NOP(), implicit, unofficial: true),
  Operation(RLA(), absoluteY, unofficial: true),
  Operation(NOP(), absoluteX, unofficial: true),
  Operation(AND(), absoluteX),
  Operation(ROL(), absoluteX),
  Operation(RLA(), absoluteX, unofficial: true),
  Operation(RTI(), implicit),
  Operation(EOR(), indexedIndirect),
  Operation(STP(), implicit, unofficial: true),
  Operation(SRE(), indexedIndirect, unofficial: true),
  Operation(NOP(), zeroPage, unofficial: true),
  Operation(EOR(), zeroPage),
  Operation(LSR(), zeroPage),
  Operation(SRE(), zeroPage, unofficial: true),
  Operation(PHA(), implicit),
  Operation(EOR(), immediate),
  Operation(LSR(), accumulator),
  Operation(ALR(), immediate, unofficial: true),
  Operation(JMP(), absolute),
  Operation(EOR(), absolute),
  Operation(LSR(), absolute),
  Operation(SRE(), absolute, unofficial: true),
  Operation(BVC(), relative),
  Operation(EOR(), indirectIndexed),
  Operation(STP(), implicit, unofficial: true),
  Operation(SRE(), indirectIndexed, unofficial: true),
  Operation(NOP(), zeroPageX, unofficial: true),
  Operation(EOR(), zeroPageX),
  Operation(LSR(), zeroPageX),
  Operation(SRE(), zeroPageX, unofficial: true),
  Operation(CLI(), implicit),
  Operation(EOR(), absoluteY),
  Operation(NOP(), implicit, unofficial: true),
  Operation(SRE(), absoluteY, unofficial: true),
  Operation(NOP(), absoluteX, unofficial: true),
  Operation(EOR(), absoluteX),
  Operation(LSR(), absoluteX),
  Operation(SRE(), absoluteX, unofficial: true),
  Operation(RTS(), implicit),
  Operation(ADC(), indexedIndirect),
  Operation(STP(), implicit, unofficial: true),
  Operation(RRA(), indexedIndirect, unofficial: true),
  Operation(NOP(), zeroPage, unofficial: true),
  Operation(ADC(), zeroPage),
  Operation(ROR(), zeroPage),
  Operation(RRA(), zeroPage, unofficial: true),
  Operation(PLA(), implicit),
  Operation(ADC(), immediate),
  Operation(ROR(), accumulator),
  Operation(ARR(), immediate, unofficial: true),
  Operation(JMP(), indirect),
  Operation(ADC(), absolute),
  Operation(ROR(), absolute),
  Operation(RRA(), absolute, unofficial: true),
  Operation(BVS(), relative),
  Operation(ADC(), indirectIndexed),
  Operation(STP(), implicit, unofficial: true),
  Operation(RRA(), indirectIndexed, unofficial: true),
  Operation(NOP(), zeroPageX, unofficial: true),
  Operation(ADC(), zeroPageX),
  Operation(ROR(), zeroPageX),
  Operation(RRA(), zeroPageX, unofficial: true),
  Operation(SEI(), implicit),
  Operation(ADC(), absoluteY),
  Operation(NOP(), implicit, unofficial: true),
  Operation(RRA(), absoluteY, unofficial: true),
  Operation(NOP(), absoluteX, unofficial: true),
  Operation(ADC(), absoluteX),
  Operation(ROR(), absoluteX),
  Operation(RRA(), absoluteX, unofficial: true),
  Operation(NOP(), immediate, unofficial: true),
  Operation(STA(), indexedIndirect),
  Operation(NOP(), immediate, unofficial: true),
  Operation(SAX(), indexedIndirect, unofficial: true),
  Operation(STY(), zeroPage),
  Operation(STA(), zeroPage),
  Operation(STX(), zeroPage),
  Operation(SAX(), zeroPage, unofficial: true),
  Operation(DEY(), implicit),
  Operation(NOP(), immediate, unofficial: true),
  Operation(TXA(), implicit),
  Operation(XAA(), immediate, unofficial: true),
  Operation(STY(), absolute),
  Operation(STA(), absolute),
  Operation(STX(), absolute),
  Operation(SAX(), absolute, unofficial: true),
  Operation(BCC(), relative),
  Operation(STA(), indirectIndexed),
  Operation(STP(), implicit, unofficial: true),
  Operation(AHX(), indirectIndexed, unofficial: true),
  Operation(STY(), zeroPageX),
  Operation(STA(), zeroPageX),
  Operation(STX(), zeroPageY),
  Operation(SAX(), zeroPageY, unofficial: true),
  Operation(TYA(), implicit),
  Operation(STA(), absoluteY),
  Operation(TXS(), implicit),
  Operation(TAS(), absoluteY, unofficial: true),
  Operation(SHY(), absoluteX, unofficial: true),
  Operation(STA(), absoluteX),
  Operation(SHX(), absoluteY, unofficial: true),
  Operation(AHX(), absoluteY, unofficial: true),
  Operation(LDY(), immediate),
  Operation(LDA(), indexedIndirect),
  Operation(LDX(), immediate),
  Operation(LAX(), indexedIndirect, unofficial: true),
  Operation(LDY(), zeroPage),
  Operation(LDA(), zeroPage),
  Operation(LDX(), zeroPage),
  Operation(LAX(), zeroPage, unofficial: true),
  Operation(TAY(), implicit),
  Operation(LDA(), immediate),
  Operation(TAX(), implicit),
  Operation(LAX(), immediate, unofficial: true),
  Operation(LDY(), absolute),
  Operation(LDA(), absolute),
  Operation(LDX(), absolute),
  Operation(LAX(), absolute, unofficial: true),
  Operation(BCS(), relative),
  Operation(LDA(), indirectIndexed),
  Operation(STP(), implicit, unofficial: true),
  Operation(LAX(), indirectIndexed, unofficial: true),
  Operation(LDY(), zeroPageX),
  Operation(LDA(), zeroPageX),
  Operation(LDX(), zeroPageY),
  Operation(LAX(), zeroPageY, unofficial: true),
  Operation(CLV(), implicit),
  Operation(LDA(), absoluteY),
  Operation(TSX(), implicit),
  Operation(LAS(), absoluteY, unofficial: true),
  Operation(LDY(), absoluteX),
  Operation(LDA(), absoluteX),
  Operation(LDX(), absoluteY),
  Operation(LAX(), absoluteY, unofficial: true),
  Operation(CPY(), immediate),
  Operation(CMP(), indexedIndirect),
  Operation(NOP(), immediate, unofficial: true),
  Operation(DCP(), indexedIndirect, unofficial: true),
  Operation(CPY(), zeroPage),
  Operation(CMP(), zeroPage),
  Operation(DEC(), zeroPage),
  Operation(DCP(), zeroPage, unofficial: true),
  Operation(INY(), implicit),
  Operation(CMP(), immediate),
  Operation(DEX(), implicit),
  Operation(AXS(), immediate, unofficial: true),
  Operation(CPY(), absolute),
  Operation(CMP(), absolute),
  Operation(DEC(), absolute),
  Operation(DCP(), absolute, unofficial: true),
  Operation(BNE(), relative),
  Operation(CMP(), indirectIndexed),
  Operation(STP(), implicit, unofficial: true),
  Operation(DCP(), indirectIndexed, unofficial: true),
  Operation(NOP(), zeroPageX, unofficial: true),
  Operation(CMP(), zeroPageX),
  Operation(DEC(), zeroPageX),
  Operation(DCP(), zeroPageX, unofficial: true),
  Operation(CLD(), implicit),
  Operation(CMP(), absoluteY),
  Operation(NOP(), implicit, unofficial: true),
  Operation(DCP(), absoluteY, unofficial: true),
  Operation(NOP(), absoluteX, unofficial: true),
  Operation(CMP(), absoluteX),
  Operation(DEC(), absoluteX),
  Operation(DCP(), absoluteX, unofficial: true),
  Operation(CPX(), immediate),
  Operation(SBC(), indexedIndirect),
  Operation(NOP(), immediate, unofficial: true),
  Operation(ISC(), indexedIndirect, unofficial: true),
  Operation(CPX(), zeroPage),
  Operation(SBC(), zeroPage),
  Operation(INC(), zeroPage),
  Operation(ISC(), zeroPage, unofficial: true),
  Operation(INX(), implicit),
  Operation(SBC(), immediate),
  Operation(NOP(), implicit),
  Operation(SBC(), immediate, unofficial: true),
  Operation(CPX(), absolute),
  Operation(SBC(), absolute),
  Operation(INC(), absolute),
  Operation(ISC(), absolute, unofficial: true),
  Operation(BEQ(), relative),
  Operation(SBC(), indirectIndexed),
  Operation(STP(), implicit, unofficial: true),
  Operation(ISC(), indirectIndexed, unofficial: true),
  Operation(NOP(), zeroPageX, unofficial: true),
  Operation(SBC(), zeroPageX),
  Operation(INC(), zeroPageX),
  Operation(ISC(), zeroPageX, unofficial: true),
  Operation(SED(), implicit),
  Operation(SBC(), absoluteY),
  Operation(NOP(), implicit, unofficial: true),
  Operation(ISC(), absoluteY, unofficial: true),
  Operation(NOP(), absoluteX, unofficial: true),
  Operation(SBC(), absoluteX),
  Operation(INC(), absoluteX),
  Operation(ISC(), absoluteX, unofficial: true),
];
