import 'package:nesd/nes/cpu/address_mode.dart';
import 'package:nesd/nes/cpu/cpu.dart';
import 'package:nesd/nes/cpu/instruction.dart';

class Operation {
  Operation(this.instruction, this.addressMode, {this.unofficial = false});

  final Instruction instruction;
  final AddressMode addressMode;
  final bool unofficial;

  void pipeline(CPU cpu) {
    final addressCycles = addressMode.pipeline(
      read: instruction.isRead,
      write: instruction.isWrite,
    );

    final instructionCycles = instruction.pipeline(addressMode.writer);

    cpu.appendCycles([
      for (var i = 0; i < addressCycles.length - 1; i++) addressCycles[i],
      if (!instruction.merge && addressCycles.isNotEmpty) addressCycles.last,
      (cpu) {
        if (instruction.merge && addressCycles.isNotEmpty) {
          addressCycles.last(cpu);
        }

        addressMode.preInstruction(cpu);

        instructionCycles.first(cpu);
      },
      for (var i = 1; i < instructionCycles.length; i++) instructionCycles[i],
    ]);
  }
}

final ops = {
  0x00: Operation(BRK, implicit),
  0x01: Operation(ORA, indexedIndirect),
  0x02: Operation(STP, implicit, unofficial: true),
  0x03: Operation(SLO, indexedIndirect, unofficial: true),
  0x04: Operation(NOP, zeroPage, unofficial: true),
  0x05: Operation(ORA, zeroPage),
  0x06: Operation(ASL, zeroPage),
  0x07: Operation(SLO, zeroPage, unofficial: true),
  0x08: Operation(PHP, implicit),
  0x09: Operation(ORA, immediate),
  0x0a: Operation(ASL, accumulator),
  0x0b: Operation(ANC, immediate, unofficial: true),
  0x0c: Operation(NOP, absolute, unofficial: true),
  0x0d: Operation(ORA, absolute),
  0x0e: Operation(ASL, absolute),
  0x0f: Operation(SLO, absolute, unofficial: true),
  0x10: Operation(BPL, relative),
  0x11: Operation(ORA, indirectIndexed),
  0x12: Operation(STP, implicit, unofficial: true),
  0x13: Operation(SLO, indirectIndexed, unofficial: true),
  0x14: Operation(NOP, zeroPageX, unofficial: true),
  0x15: Operation(ORA, zeroPageX),
  0x16: Operation(ASL, zeroPageX),
  0x17: Operation(SLO, zeroPageX, unofficial: true),
  0x18: Operation(CLC, implicit),
  0x19: Operation(ORA, absoluteY),
  0x1a: Operation(NOP, implicit, unofficial: true),
  0x1b: Operation(SLO, absoluteY, unofficial: true),
  0x1c: Operation(NOP, absoluteX, unofficial: true),
  0x1d: Operation(ORA, absoluteX),
  0x1e: Operation(ASL, absoluteX),
  0x1f: Operation(SLO, absoluteX, unofficial: true),
  0x20: Operation(JSR, absolute),
  0x21: Operation(AND, indexedIndirect),
  0x22: Operation(STP, implicit, unofficial: true),
  0x23: Operation(RLA, indexedIndirect, unofficial: true),
  0x24: Operation(BIT, zeroPage),
  0x25: Operation(AND, zeroPage),
  0x26: Operation(ROL, zeroPage),
  0x27: Operation(RLA, zeroPage, unofficial: true),
  0x28: Operation(PLP, implicit),
  0x29: Operation(AND, immediate),
  0x2a: Operation(ROL, accumulator),
  0x2b: Operation(ANC, immediate, unofficial: true),
  0x2c: Operation(BIT, absolute),
  0x2d: Operation(AND, absolute),
  0x2e: Operation(ROL, absolute),
  0x2f: Operation(RLA, absolute, unofficial: true),
  0x30: Operation(BMI, relative),
  0x31: Operation(AND, indirectIndexed),
  0x32: Operation(STP, implicit, unofficial: true),
  0x33: Operation(RLA, indirectIndexed, unofficial: true),
  0x34: Operation(NOP, zeroPageX, unofficial: true),
  0x35: Operation(AND, zeroPageX),
  0x36: Operation(ROL, zeroPageX),
  0x37: Operation(RLA, zeroPageX, unofficial: true),
  0x38: Operation(SEC, implicit),
  0x39: Operation(AND, absoluteY),
  0x3a: Operation(NOP, implicit, unofficial: true),
  0x3b: Operation(RLA, absoluteY, unofficial: true),
  0x3c: Operation(NOP, absoluteX, unofficial: true),
  0x3d: Operation(AND, absoluteX),
  0x3e: Operation(ROL, absoluteX),
  0x3f: Operation(RLA, absoluteX, unofficial: true),
  0x40: Operation(RTI, implicit),
  0x41: Operation(EOR, indexedIndirect),
  0x42: Operation(STP, implicit, unofficial: true),
  0x43: Operation(SRE, indexedIndirect, unofficial: true),
  0x44: Operation(NOP, zeroPage, unofficial: true),
  0x45: Operation(EOR, zeroPage),
  0x46: Operation(LSR, zeroPage),
  0x47: Operation(SRE, zeroPage, unofficial: true),
  0x48: Operation(PHA, implicit),
  0x49: Operation(EOR, immediate),
  0x4a: Operation(LSR, accumulator),
  0x4b: Operation(ALR, immediate, unofficial: true),
  0x4c: Operation(JMP, absolute),
  0x4d: Operation(EOR, absolute),
  0x4e: Operation(LSR, absolute),
  0x4f: Operation(SRE, absolute, unofficial: true),
  0x50: Operation(BVC, relative),
  0x51: Operation(EOR, indirectIndexed),
  0x52: Operation(STP, implicit, unofficial: true),
  0x53: Operation(SRE, indirectIndexed, unofficial: true),
  0x54: Operation(NOP, zeroPageX, unofficial: true),
  0x55: Operation(EOR, zeroPageX),
  0x56: Operation(LSR, zeroPageX),
  0x57: Operation(SRE, zeroPageX, unofficial: true),
  0x58: Operation(CLI, implicit),
  0x59: Operation(EOR, absoluteY),
  0x5a: Operation(NOP, implicit, unofficial: true),
  0x5b: Operation(SRE, absoluteY, unofficial: true),
  0x5c: Operation(NOP, absoluteX, unofficial: true),
  0x5d: Operation(EOR, absoluteX),
  0x5e: Operation(LSR, absoluteX),
  0x5f: Operation(SRE, absoluteX, unofficial: true),
  0x60: Operation(RTS, implicit),
  0x61: Operation(ADC, indexedIndirect),
  0x62: Operation(STP, implicit, unofficial: true),
  0x63: Operation(RRA, indexedIndirect, unofficial: true),
  0x64: Operation(NOP, zeroPage, unofficial: true),
  0x65: Operation(ADC, zeroPage),
  0x66: Operation(ROR, zeroPage),
  0x67: Operation(RRA, zeroPage, unofficial: true),
  0x68: Operation(PLA, implicit),
  0x69: Operation(ADC, immediate),
  0x6a: Operation(ROR, accumulator),
  0x6b: Operation(ARR, immediate, unofficial: true),
  0x6c: Operation(JMP, indirect),
  0x6d: Operation(ADC, absolute),
  0x6e: Operation(ROR, absolute),
  0x6f: Operation(RRA, absolute, unofficial: true),
  0x70: Operation(BVS, relative),
  0x71: Operation(ADC, indirectIndexed),
  0x72: Operation(STP, implicit, unofficial: true),
  0x73: Operation(RRA, indirectIndexed, unofficial: true),
  0x74: Operation(NOP, zeroPageX, unofficial: true),
  0x75: Operation(ADC, zeroPageX),
  0x76: Operation(ROR, zeroPageX),
  0x77: Operation(RRA, zeroPageX, unofficial: true),
  0x78: Operation(SEI, implicit),
  0x79: Operation(ADC, absoluteY),
  0x7a: Operation(NOP, implicit, unofficial: true),
  0x7b: Operation(RRA, absoluteY, unofficial: true),
  0x7c: Operation(NOP, absoluteX, unofficial: true),
  0x7d: Operation(ADC, absoluteX),
  0x7e: Operation(ROR, absoluteX),
  0x7f: Operation(RRA, absoluteX, unofficial: true),
  0x80: Operation(NOP, immediate, unofficial: true),
  0x81: Operation(STA, indexedIndirect),
  0x82: Operation(NOP, immediate, unofficial: true),
  0x83: Operation(SAX, indexedIndirect, unofficial: true),
  0x84: Operation(STY, zeroPage),
  0x85: Operation(STA, zeroPage),
  0x86: Operation(STX, zeroPage),
  0x87: Operation(SAX, zeroPage, unofficial: true),
  0x88: Operation(DEY, implicit),
  0x89: Operation(NOP, immediate, unofficial: true),
  0x8a: Operation(TXA, implicit),
  0x8b: Operation(XAA, immediate, unofficial: true),
  0x8c: Operation(STY, absolute),
  0x8d: Operation(STA, absolute),
  0x8e: Operation(STX, absolute),
  0x8f: Operation(SAX, absolute, unofficial: true),
  0x90: Operation(BCC, relative),
  0x91: Operation(STA, indirectIndexed),
  0x92: Operation(STP, implicit, unofficial: true),
  0x93: Operation(AHX, indirectIndexed, unofficial: true),
  0x94: Operation(STY, zeroPageX),
  0x95: Operation(STA, zeroPageX),
  0x96: Operation(STX, zeroPageY),
  0x97: Operation(SAX, zeroPageY, unofficial: true),
  0x98: Operation(TYA, implicit),
  0x99: Operation(STA, absoluteY),
  0x9a: Operation(TXS, implicit),
  0x9b: Operation(TAS, absoluteY, unofficial: true),
  0x9c: Operation(SHY, absoluteX, unofficial: true),
  0x9d: Operation(STA, absoluteX),
  0x9e: Operation(SHX, absoluteY, unofficial: true),
  0x9f: Operation(AHX, absoluteY, unofficial: true),
  0xa0: Operation(LDY, immediate),
  0xa1: Operation(LDA, indexedIndirect),
  0xa2: Operation(LDX, immediate),
  0xa3: Operation(LAX, indexedIndirect, unofficial: true),
  0xa4: Operation(LDY, zeroPage),
  0xa5: Operation(LDA, zeroPage),
  0xa6: Operation(LDX, zeroPage),
  0xa7: Operation(LAX, zeroPage, unofficial: true),
  0xa8: Operation(TAY, implicit),
  0xa9: Operation(LDA, immediate),
  0xaa: Operation(TAX, implicit),
  0xab: Operation(LAX, immediate, unofficial: true),
  0xac: Operation(LDY, absolute),
  0xad: Operation(LDA, absolute),
  0xae: Operation(LDX, absolute),
  0xaf: Operation(LAX, absolute, unofficial: true),
  0xb0: Operation(BCS, relative),
  0xb1: Operation(LDA, indirectIndexed),
  0xb2: Operation(STP, implicit, unofficial: true),
  0xb3: Operation(LAX, indirectIndexed, unofficial: true),
  0xb4: Operation(LDY, zeroPageX),
  0xb5: Operation(LDA, zeroPageX),
  0xb6: Operation(LDX, zeroPageY),
  0xb7: Operation(LAX, zeroPageY, unofficial: true),
  0xb8: Operation(CLV, implicit),
  0xb9: Operation(LDA, absoluteY),
  0xba: Operation(TSX, implicit),
  0xbb: Operation(LAS, absoluteY, unofficial: true),
  0xbc: Operation(LDY, absoluteX),
  0xbd: Operation(LDA, absoluteX),
  0xbe: Operation(LDX, absoluteY),
  0xbf: Operation(LAX, absoluteY, unofficial: true),
  0xc0: Operation(CPY, immediate),
  0xc1: Operation(CMP, indexedIndirect),
  0xc2: Operation(NOP, immediate, unofficial: true),
  0xc3: Operation(DCP, indexedIndirect, unofficial: true),
  0xc4: Operation(CPY, zeroPage),
  0xc5: Operation(CMP, zeroPage),
  0xc6: Operation(DEC, zeroPage),
  0xc7: Operation(DCP, zeroPage, unofficial: true),
  0xc8: Operation(INY, implicit),
  0xc9: Operation(CMP, immediate),
  0xca: Operation(DEX, implicit),
  0xcb: Operation(AXS, immediate, unofficial: true),
  0xcc: Operation(CPY, absolute),
  0xcd: Operation(CMP, absolute),
  0xce: Operation(DEC, absolute),
  0xcf: Operation(DCP, absolute, unofficial: true),
  0xd0: Operation(BNE, relative),
  0xd1: Operation(CMP, indirectIndexed),
  0xd2: Operation(STP, implicit, unofficial: true),
  0xd3: Operation(DCP, indirectIndexed, unofficial: true),
  0xd4: Operation(NOP, zeroPageX, unofficial: true),
  0xd5: Operation(CMP, zeroPageX),
  0xd6: Operation(DEC, zeroPageX),
  0xd7: Operation(DCP, zeroPageX, unofficial: true),
  0xd8: Operation(CLD, implicit),
  0xd9: Operation(CMP, absoluteY),
  0xda: Operation(NOP, implicit, unofficial: true),
  0xdb: Operation(DCP, absoluteY, unofficial: true),
  0xdc: Operation(NOP, absoluteX, unofficial: true),
  0xdd: Operation(CMP, absoluteX),
  0xde: Operation(DEC, absoluteX),
  0xdf: Operation(DCP, absoluteX, unofficial: true),
  0xe0: Operation(CPX, immediate),
  0xe1: Operation(SBC, indexedIndirect),
  0xe2: Operation(NOP, immediate, unofficial: true),
  0xe3: Operation(ISC, indexedIndirect, unofficial: true),
  0xe4: Operation(CPX, zeroPage),
  0xe5: Operation(SBC, zeroPage),
  0xe6: Operation(INC, zeroPage),
  0xe7: Operation(ISC, zeroPage, unofficial: true),
  0xe8: Operation(INX, implicit),
  0xe9: Operation(SBC, immediate),
  0xea: Operation(NOP, implicit),
  0xeb: Operation(SBC, immediate, unofficial: true),
  0xec: Operation(CPX, absolute),
  0xed: Operation(SBC, absolute),
  0xee: Operation(INC, absolute),
  0xef: Operation(ISC, absolute, unofficial: true),
  0xf0: Operation(BEQ, relative),
  0xf1: Operation(SBC, indirectIndexed),
  0xf2: Operation(STP, implicit, unofficial: true),
  0xf3: Operation(ISC, indirectIndexed, unofficial: true),
  0xf4: Operation(NOP, zeroPageX, unofficial: true),
  0xf5: Operation(SBC, zeroPageX),
  0xf6: Operation(INC, zeroPageX),
  0xf7: Operation(ISC, zeroPageX, unofficial: true),
  0xf8: Operation(SED, implicit),
  0xf9: Operation(SBC, absoluteY),
  0xfa: Operation(NOP, implicit, unofficial: true),
  0xfb: Operation(ISC, absoluteY, unofficial: true),
  0xfc: Operation(NOP, absoluteX, unofficial: true),
  0xfd: Operation(SBC, absoluteX),
  0xfe: Operation(INC, absoluteX),
  0xff: Operation(ISC, absoluteX, unofficial: true),
};
