name: CI pipeline
on: [push]

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - id: env
        run: ci/env.sh
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.env.outputs.flutter_version }}
          cache: true
      - run: flutter pub get
      - run: dart format --set-exit-if-changed .
      - run: flutter analyze

  test:
    runs-on: ubuntu-22.04
    needs: [lint]
    steps:
      - uses: actions/checkout@v5
      - id: env
        run: ci/env.sh
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.env.outputs.flutter_version }}
          cache: true
      - uses: hrishikesh-kadam/setup-lcov@v1
      - uses: actions/cache@v4
        with:
          key: lcov
          path: |
            /usr/bin
      - run: flutter pub get
      - run: flutter test --coverage
      - run: ci/0-test/extract_coverage.sh
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './pages'

  publish-coverage:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    needs: [test]
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/configure-pages@v5
      - id: deployment
        uses: actions/deploy-pages@v4

  build-macos:
    runs-on: macos-latest
    needs: [test]
    outputs:
      release_name: ${{ steps.env.outputs.release_name }}
    steps:
      - uses: actions/checkout@v5
      - id: env
        run: ci/env.sh
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.env.outputs.flutter_version }}
          cache: true
      - uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: |
            ${{ secrets.GAMEPADS_PRIVATE_KEY }}
            ${{ secrets.MP_AUDIO_STREAM_PRIVATE_KEY }}
      - run: ci/1-build/prepare.sh
      - run: ci/1-build/macos/prepare.sh
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      - run: ci/1-build/macos/build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.env.outputs.artifact_flavored }}.macos-universal.dmg
          path: '*.dmg'
          if-no-files-found: error

  build-linux:
    strategy:
      matrix:
        arch: [ x64, arm64 ]
    runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-22.04-arm' || 'ubuntu-22.04' }}
    needs: [ test ]
    steps:
      - uses: actions/checkout@v5
      - id: env
        run: ci/env.sh ${{ matrix.arch }}
      - uses: subosito/flutter-action@v2
        with:
          channel: master
          flutter-version: ${{ steps.env.outputs.flutter_version }}
          cache: true
      - run: ci/1-build/prepare.sh
      - run: ci/1-build/linux/build.sh
      - uses: actions/cache/save@v4
        with:
          path: build/linux/${{ matrix.arch }}/release/bundle
          key: linux-${{ matrix.arch }}-${{ github.sha }}

  build-windows:
    runs-on: windows-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v5
      - run: ci/1-build/windows/prepare.ps1
      - id: env
        shell: bash
        run: |
          alias yq="/C/ProgramData/chocolatey/lib/yq/tools/yq.exe"
          alias jq="/C/ProgramData/chocolatey/lib/jq/tools/jq.exe"
          ci/env.sh
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.env.outputs.flutter_version }}
          cache: true
      - run: ci/1-build/windows/build.ps1
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.env.outputs.artifact }}.windows-x64.zip
          path: dist/
          if-no-files-found: error

  build-android:
    runs-on: ubuntu-22.04
    needs: [test]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle
      - id: env
        run: ci/env.sh
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.env.outputs.flutter_version }}
          cache: true
      - run: ci/1-build/prepare.sh
      - run: ci/1-build/android/prepare.sh
        env:
          KEY_STORE_BASE64: ${{ secrets.ANDROID_KEY_STORE }}
          KEY_PROPERTIES: ${{ secrets.ANDROID_KEY_PROPERTIES }}
      - run: ci/1-build/android/build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.env.outputs.artifact_flavored }}.android.apk
          path: '*.apk'
          if-no-files-found: error

  package-linux-deb:
    strategy:
      matrix:
        arch: [ x64, arm64 ]
    runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-22.04-arm' || 'ubuntu-22.04' }}
    needs: [ build-linux ]
    steps:
      - uses: actions/checkout@v5
      - id: env
        run: ci/env.sh ${{ matrix.arch }}
      - uses: actions/cache/restore@v4
        with:
          path: build/linux/${{ matrix.arch }}/release/bundle
          key: linux-${{ matrix.arch }}-${{ github.sha }}
      - run: ci/2-package/linux/package_deb.sh
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.env.outputs.artifact }}.linux-${{ matrix.arch }}.deb
          path: '*.deb'
          if-no-files-found: error

  package-linux-rpm:
    strategy:
      matrix:
        arch: [ x64, arm64 ]
    runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-22.04-arm' || 'ubuntu-22.04' }}
    needs: [ build-linux ]
    steps:
      - uses: actions/checkout@v5
      - id: env
        run: ci/env.sh ${{ matrix.arch }}
      - uses: actions/cache/restore@v4
        with:
          path: build/linux/${{ matrix.arch }}/release/bundle
          key: linux-${{ matrix.arch }}-${{ github.sha }}
      - run: ci/2-package/linux/package_rpm.sh
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.env.outputs.artifact }}.linux-${{ matrix.arch }}.rpm
          path: '*.rpm'
          if-no-files-found: error

  package-linux-flatpak:
    strategy:
      matrix:
        arch: [ x64, arm64 ]
    runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-22.04-arm' || 'ubuntu-22.04' }}
    needs: [ build-linux ]
    container:
      image: ghcr.io/andyholmes/flatter/freedesktop:24.08
      options: --privileged
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - run: |
          git config --global --add safe.directory $(pwd)
          sudo dnf install -y yq jq
      - id: env
        run: ci/env.sh ${{ matrix.arch }}
      - uses: actions/cache/restore@v4
        with:
          path: build/linux/${{ matrix.arch }}/release/bundle
          key: linux-${{ matrix.arch }}-${{ github.sha }}
      - uses: actions/checkout@v5
        with:
          repository: jpjonte/flatpak
          ssh-key: ${{ secrets.FLATPAK_PRIVATE_KEY }}
          ref: main
          path: flatpak
      - if: startsWith(github.ref, 'refs/tags/')
        run: ln -s flatpak/stable repo
      - if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        run: ln -s flatpak/nightly repo
      - id: gpg-key
        run: ci/2-package/linux/select_gpg_key.sh
        env:
          FLATPAK_STABLE_GPG_PRIVATE_KEY: ${{ secrets.FLATPAK_STABLE_GPG_PRIVATE_KEY }}
          FLATPAK_STABLE_GPG_PASSPHRASE: ${{ secrets.FLATPAK_STABLE_GPG_PASSPHRASE }}
          FLATPAK_NIGHTLY_GPG_PRIVATE_KEY: ${{ secrets.FLATPAK_NIGHTLY_GPG_PRIVATE_KEY }}
          FLATPAK_NIGHTLY_GPG_PASSPHRASE: ${{ secrets.FLATPAK_NIGHTLY_GPG_PASSPHRASE }}
      - id: gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ steps.gpg-key.outputs.gpg_private_key }}
          passphrase: ${{ steps.gpg-key.outputs.gpg_passphrase }}
      - uses: andyholmes/flatter@main
        with:
          files: linux/packaging/dev.jpj.NESd.json
          arch: ${{ matrix.arch == 'x64' && 'x86_64' || 'aarch64' }}
          gpg-sign: ${{ steps.gpg.outputs.fingerprint }}
          cache-key: flatter-${{ github.sha }}
      - run: ci/2-package/linux/package_flatpak.sh
        env:
          GPG_KEY_ID: ${{ steps.gpg.outputs.fingerprint }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.env.outputs.artifact }}.linux-${{ matrix.arch }}.flatpak
          path: '*.flatpak'
          if-no-files-found: error
      - uses: actions/cache/save@v4
        with:
          path: flatpak/stable
          key: flatpak-stable-${{ github.sha }}
      - uses: actions/cache/save@v4
        with:
          path: flatpak/nightly
          key: flatpak-nightly-${{ github.sha }}

  package-linux-appimage:
    strategy:
      matrix:
        arch: [ x64, arm64 ]
    runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-22.04-arm' || 'ubuntu-22.04' }}
    needs: [ build-linux ]
    steps:
      - uses: actions/checkout@v5
      - id: env
        run: ci/env.sh ${{ matrix.arch }}
      - uses: actions/cache/restore@v4
        with:
          path: build/linux/${{ matrix.arch }}/release/bundle
          key: linux-${{ matrix.arch }}-${{ github.sha }}
      - run: ci/2-package/linux/package_appimage.sh
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.env.outputs.artifact }}.linux-${{ matrix.arch }}.AppImage
          path: '*.AppImage'
          if-no-files-found: error

  release_nightly:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    needs:
      - build-macos
      - package-linux-deb
      - package-linux-rpm
      - package-linux-flatpak
      - package-linux-appimage
      - build-windows
      - build-android
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/checkout@v5
        with:
          repository: jpjonte/flatpak
          ssh-key: ${{ secrets.FLATPAK_PRIVATE_KEY }}
          ref: main
          path: flatpak
      - uses: actions/cache/restore@v4
        with:
          path: flatpak/nightly
          key: flatpak-nightly-${{ github.sha }}
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Update NESd nightly
          commit_user_name: NESd CI Pipeline
          commit_user_email: nesd@jpj.dev
          commit_author: NESd CI Pipeline <nesd@jpj.dev>
          repository: flatpak
          skip_fetch: true
          skip_checkout: true
      - id: changelog
        run: ci/3-release/extract_changelog_nightly.sh
      - uses: actions/download-artifact@v5
        with:
          path: artifacts
          merge-multiple: true
      - id: env
        run: ci/env.sh
      - run: ci/3-release/zip_windows_artifacts.sh
      - run: gh release delete nightly --cleanup-tag -y
      - uses: ncipollo/release-action@v1
        with:
          artifacts: artifacts/*
          name: NESd nightly
          tag: nightly
          body: ${{ steps.changelog.outputs.changes }}
          artifactErrorsFailBuild: true
          prerelease: true
          allowUpdates: true
          removeArtifacts: true

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    needs:
      - build-macos
      - package-linux-deb
      - package-linux-rpm
      - package-linux-flatpak
      - package-linux-appimage
      - build-windows
      - build-android
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/checkout@v5
        with:
          repository: jpjonte/flatpak
          ssh-key: ${{ secrets.FLATPAK_PRIVATE_KEY }}
          ref: main
          path: flatpak
      - uses: actions/cache/restore@v4
        with:
          path: flatpak/stable
          key: flatpak-stable-${{ github.sha }}
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Update NESd stable
          commit_user_name: NESd CI Pipeline
          commit_user_email: nesd@jpj.dev
          commit_author: NESd CI Pipeline <nesd@jpj.dev>
          repository: flatpak
          skip_fetch: true
          skip_checkout: true
      - id: changelog
        run: ci/3-release/extract_changelog.sh
      - uses: actions/download-artifact@v5
        with:
          path: artifacts
          merge-multiple: true
      - id: env
        run: ci/env.sh
      - run: ci/3-release/zip_windows_artifacts.sh
      - uses: ncipollo/release-action@v1
        with:
          artifacts: artifacts/*
          name: NESd ${{ needs.build-macos.outputs.release_name }}
          body: ${{ steps.changelog.outputs.changes }}
          artifactErrorsFailBuild: true
