name: CI pipeline
on: [push]
jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.GAMEPADS_PRIVATE_KEY }}
            ${{ secrets.MP_AUDIO_STREAM_PRIVATE_KEY }}
      - run: ci/build/prepare.sh
      - run: ci/build/macos/prepare.sh
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      - run: ci/build/macos/build.sh
      - id: env
        run: ci/build/env.sh
      - uses: actions/upload-artifact@v4
        with:
          name: NESd ${{ steps.env.outputs.release_name }} macOS
          path: ${{ steps.env.outputs.macos_path }}
          if-no-files-found: error

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.GAMEPADS_PRIVATE_KEY }}
            ${{ secrets.MP_AUDIO_STREAM_PRIVATE_KEY }}
      - run: ci/build/prepare.sh
      - run: ci/build/linux/prepare.sh
      - run: ci/build/linux/build.sh
      - id: env
        run: ci/build/env.sh
      - uses: actions/upload-artifact@v4
        with:
          name: NESd ${{ steps.env.outputs.release_name }} Linux deb
          path: ${{ steps.env.outputs.linux_deb_path }}
          if-no-files-found: error
      - uses: actions/upload-artifact@v4
        with:
          name: NESd ${{ steps.env.outputs.release_name }} Linux rpm
          path: ${{ steps.env.outputs.linux_rpm_path }}
          if-no-files-found: error

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: ci/build/windows/prepare.ps1
      - run: ci/build/windows/build.ps1
      - id: env
        shell: bash
        run: |
          alias yq="/C/ProgramData/chocolatey/lib/yq/tools/yq.exe"
          ci/build/env.sh
      - uses: actions/upload-artifact@v4
        with:
          name: NESd ${{ steps.env.outputs.release_name }} Windows
          path: ${{ steps.env.outputs.windows_path }}
          if-no-files-found: error
